# Generated by Django 5.0.6 on 2024-07-22 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_alter_payment_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fapp.addproduct'),
            preserve_default=False,
        ),
    ]
