# Generated by Django 5.0.6 on 2024-07-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0007_cartpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartpayment',
            old_name='cart',
            new_name='mycart',
        ),
    ]
