# Generated by Django 5.0.6 on 2024-07-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_rename_cart_cartpayment_mycart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartpayment',
            name='mycart',
        ),
        migrations.AddField(
            model_name='cartpayment',
            name='pdctdetails',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
