# Generated by Django 5.0.6 on 2024-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0010_alter_cartpayment_pdctdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
