# Generated by Django 5.0.6 on 2024-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0012_cartpayment_farmer_cartpayment_fremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='totalprice',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
