# Generated by Django 5.0.6 on 2024-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0013_cartpayment_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
