# Generated by Django 5.0.6 on 2024-07-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0019_cartpayment_cartuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='frorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruname', models.CharField(max_length=400)),
                ('proprice', models.IntegerField(default=0)),
                ('pitm', models.CharField(max_length=400)),
                ('pcount', models.IntegerField(default=0)),
                ('ptotal', models.IntegerField(default=0)),
            ],
        ),
    ]
