# Generated by Django 5.0.6 on 2024-08-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0021_frorder_fuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
