# Generated by Django 5.0.6 on 2024-08-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0022_addproduct_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
