# Generated by Django 5.0.6 on 2024-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0023_alter_cartpayment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='frorder',
            name='deliverystatus',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartpayment',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
