# Generated by Django 5.0.6 on 2024-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0025_payment_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='deliverystatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
