# Generated by Django 5.0.6 on 2024-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0026_alter_payment_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpayment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='frorder',
            name='deliverystatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
